version: "3.7"

# Volumes for persisted data.
volumes:
  data_sendy:
    labels:
      co.sendy.description: "Data volume for Sendy Database."

services:
  # Database: MySQL
  db_sendy:
    hostname: db_sendy
    container_name: db_sendy
    image: mysql:5.6
    env_file:
      - sendy.env
    volumes:
      - data_sendy:/var/lib/mysql

  # WebApp: Apache2+PHP+Sendy
  sendy:
    hostname: sendy
    container_name: sendy
    depends_on:
      - db_sendy
    image: sendy:latest
    build:
      context: .
      # Uncomment to enabled XDEBUG build
      # target: debug
    env_file:
      - sendy.env
    ports:
      - 8080:80
